name: rating_dialog
description: A beautiful and customizable Star Rating Dialog package for Flutter
version: 1.0.0
author: Oliver Martinez <nemoryoliver@gmail.com>
homepage: https://github.com/nemoryoliver/rating_dialog

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: